python main.py --is_conf --target_conf AAAI --conf_year 2022 --conf_keyword diffusion
python main.py --is_conf --target_conf AAAI --conf_year 2022 --conf_keyword capacity
python main.py --is_conf --target_conf AAAI --conf_year 2022 --conf_keyword train
python main.py --is_conf --target_conf AAAI --conf_year 2022 --conf_keyword curriculum
python main.py --is_conf --target_conf ICML --conf_year 2022 --conf_keyword diffusion
python main.py --is_conf --target_conf ICML --conf_year 2022 --conf_keyword capacity
python main.py --is_conf --target_conf ICML --conf_year 2022 --conf_keyword train
python main.py --is_conf --target_conf ICML --conf_year 2022 --conf_keyword curriculum
python main.py --is_conf --target_conf NIPS --conf_year 2022 --conf_keyword diffusion
python main.py --is_conf --target_conf NIPS --conf_year 2022 --conf_keyword capacity
python main.py --is_conf --target_conf NIPS --conf_year 2022 --conf_keyword train
python main.py --is_conf --target_conf NIPS --conf_year 2022 --conf_keyword curriculum
python main.py --is_conf --target_conf ICLR --conf_year 2022 --conf_keyword diffusion
python main.py --is_conf --target_conf ICLR --conf_year 2022 --conf_keyword capacity
python main.py --is_conf --target_conf ICLR --conf_year 2022 --conf_keyword train
python main.py --is_conf --target_conf ICLR --conf_year 2022 --conf_keyword curriculum
